[project]
name = "video-stuff"
version = "0.1.0"
requires-python = ">= 3.12"
dependencies = [
    "moviepy~=2.1.1",
    "opencv-python~=4.10.0.84",
    "numpy~=2.0.2",
    "scipy~=1.14.1",
    "tqdm~=4.67.1",
    "librosa~=0.10.2.post1",
    "soundfile~=0.12.1",
]
